### PR TITLE
fix: form not submitting on keyboard enter

### LINKED ISSUE #850: Keyboard enter not triggering form submission on password input
### Describe the bug
In password input keyboard enter is not triggering form submission , it felt weird that enter was not working

### To Reproduce
 
Go to  https://app.infisical.com/login/sso?token=1234

### Expected behavior
  After password entering keyboard enter should trigger form submission

### Screenshots

image

### Platform you are having the issue on:
Arc browser , mac os , cloud version

### PR DESCRIPTION
**Pull request by sreehari2003**
# Description 📣

- closes #850 

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️
 I did some manual testing and it is working ok
```sh
  https://app.infisical.com/login/sso?token=randomnumber

```
 is breaking your client  side , I think it should be fixed
---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

### CODE REVIEW

File: frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx [hunk 1]
```diff
@@ -127,6 +127,7 @@ export const PasswordStep = ({
             </div>
             <div className='lg:w-1/6 w-1/4 w-full mx-auto flex items-center justify-center min-w-[22rem] text-center rounded-md mt-4'>
                 <Button
+                    type="submit"
                     colorSchema="primary" 
                     variant="outline_bg"
                     onClick={async () => handleLogin()}
```
Comment (akhilmhdh) [inline frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx:133]: Can you please move this onClick to onSubmit in the form component. because this is not a good pattern to put both submit and onClick here

File: frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx [hunk 2]
```diff
@@ -36,6 +37,7 @@ export const SAMLSSOStep = ({
             </div>
             <div className='lg:w-1/6 w-1/4 w-full mx-auto flex items-center justify-center min-w-[20rem] md:min-w-[22rem] text-center rounded-md mt-4'>
                 <Button
+                    type="submit" 
                     colorSchema="primary" 
                     variant="outline_bg"
                     onClick={() => {
```
Comment (akhilmhdh) [inline frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx:43]: Same goes here

**Review by akhilmhdh — CHANGES_REQUESTED** [review]

File: frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx (hunk 2 above)
Comment (sreehari2003) [reply frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx]: done

**Review by akhilmhdh — APPROVED** [review]
