### PR TITLE
fix: access control member search returns empty results when search using upper case…

### LINKED ISSUE #1434: Access Control member search returns empty if search term has uppercase letters
### Describe the bug
Making a search with an uppercase letter returns an empty result list in any Access Control pages (Organization and Project).

### To Reproduce
1. Go to either Project's or Organization's Access Control
2. Make a search with all lowercase letters
3. You should see matches
4. Now make the same search but with one or more capitalized letters
5. You should see no matches at all

### Expected behavior
Searches should be case-insensitive; searches with capitalized letters should have matches, not an empty list.

### Screenshots
Screenshot 2024-02-21 at 10 01 22 PM
but this matches:
Screenshot 2024-02-21 at 10 01 47 PM

### Platform you are having the issue on:
Web, MacOS, on Chromium browser.

### Additional context
Open to send in a PR.

### PR DESCRIPTION
**Pull request by Nithishvb**
… letters.

# Description 📣

Closes #1434

This pull request addresses a bug that caused empty search results when searching with uppercase letters. The issue occurred due to case sensitivity in search queries, leading to mismatches between lowercase data and uppercase search terms.

Changes Made:

* Modified the search functionality to perform case-insensitive comparisons.

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

### CODE REVIEW

File: frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx [hunk 1]
```diff
@@ -141,10 +141,10 @@ export const OrgMembersTable = ({ handlePopUpOpen, setCompleteInviteLink }: Prop
     () =>
       members?.filter(
         ({ user: u, inviteEmail }) =>
-          u?.firstName?.toLowerCase().includes(searchMemberFilter) ||
-          u?.lastName?.toLowerCase().includes(searchMemberFilter) ||
-          u?.email?.toLowerCase().includes(searchMemberFilter) ||
-          inviteEmail?.includes(searchMemberFilter)
+          u?.firstName?.toLowerCase().includes(searchMemberFilter.toLowerCase()) ||
```
Comment (maidul98) [inline frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx:144]: Instead of changing each searchMemberFilter, you can just change all to be lower case via `setSearchMemberFilter`

Comment (Nithishvb) [reply frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx:144]: Hi @maidul98  , thank you for your review, When we use `setSearchMemberFilter` to update the state, such as `setSearchMemberFilter(e.target.value.toLowerCase())`, the user is unable to search in uppercase, even when they attempt to do so; the uppercase word is converted to smaller case in the search field itself.

Comment (akhilmhdh) [reply frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx:144]: Correct. Agreed. The other one user will be confused because when they type the casing gets converted

**Review by akhilmhdh — APPROVED** [review]
