### PR TITLE
Fix: Restricted Secret Environment UI Corrections

### LINKED ISSUE #2371: Missing secrets warning show to users who do not have access to the secrets of an enviornment
### Describe the bug
Users without access to the secrets of an environment appear as if they aren't set on the secrets overview page

### To Reproduce
1. Deny access to the secrets of an environment for a role/user
image
2. Go to the secrets overview page

### Expected behavior
Either the environment is hidden, or the missing secrets indicator is not shown, and the explore button is disabled.

### Screenshots
image
image

Clicking explore:
image

### PR DESCRIPTION
**Pull request by scott-ray-wilson**
# Description 📣

This PR hides environments the user does not have read access to on the secrets overview page. Also includes increased default pagination size for secrets and identities from 10 to 50 and temporary fix to prevent expanded secrets component width being set to 0.

image
(Example user without production env read permissions)

resolves #2371

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

```sh
# Here's some code block to paste some code snippets
```

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

### CODE REVIEW

File: frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx [hunk 1]
```diff
@@ -173,11 +173,31 @@ export const SecretOverviewPage = () => {
...
+        })
+      )
+    )
+  );
 
   useEffect(() => {
-    setVisibleEnvs(userAvailableEnvs);
-  }, [userAvailableEnvs]);
+    setVisibleEnvs(
+      userAvailableEnvs?.filter(({ slug }) =>
```
Comment (maidul98) [inline frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx:190]: Can we also hide it here?

CleanShot 2024-09-14 at 23 21 12@2x

**Review by maidul98 — COMMENTED** [review]
Looks good to me, just left one comment

File: frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx (hunk 1 above)
Comment (scott-ray-wilson) [reply frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx:190]: Nice catch!
image

I noticed I missed it here as well, fixed:
image

**Review by maidul98 — APPROVED** [review]
